%% Copyright 2014 MERCIER David
function handles = TriDiMap_setGUI(module)
%% Definition of the GUI and buttons
g = guidata(gcf);
handles = g.handles;

%% Title of the GUI
handles.title_GUI_1 = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.31 0.96 0.6 0.04],...
    'String', 'Mapping of mechanical properties from (nano)indentation experiments.',...
    'FontWeight', 'bold',...
    'FontSize', 12,...
    'HorizontalAlignment', 'center',...
    'ForegroundColor', 'red');

handles.title_GUI_2 = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.31 0.93 0.6 0.03],...
    'String', strcat('Version_', ...
    g.config.version_toolbox, ' - Copyright 2014 MERCIER David'),...
    'FontSize', 10);

set([handles.title_GUI_1, handles.title_GUI_2], ...
    'FontWeight', 'bold',...
    'HorizontalAlignment', 'center',...
    'ForegroundColor', 'red')

%% Date / Time
handles.date_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'text',...
    'String', datestr(datenum(clock),'mmm.dd,yyyy HH:MM'),...
    'Position', [0.92 0.975 0.075 0.02]);

%% Buttons to set type of files
handles.pm_set_file = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'popupmenu',...
    'Position', [0.02 0.95 0.08 0.04],...
    'String', {'Agilent MTS';'Hysitron';'ASMEC';'other'},...
    'Value', 1,...
    'Callback', '');

%% Units
% Unit definition for the X and Y size
handles.title_unitLength_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.11 0.97 0.04 0.02],...
    'String', 'Length:',...
    'HorizontalAlignment', 'left');

handles.unitLength_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'popupmenu',...
    'Position', [0.15 0.97 0.05 0.02],...
    'String', listUnitLength,...
    'Value', 2);

% Unit definition for the property
handles.title_unitProp_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.21 0.97 0.04 0.02],...
    'String', 'Property:',...
    'HorizontalAlignment', 'left');

handles.unitProp_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'popupmenu',...
    'Position', [0.25 0.97 0.05 0.02],...
    'String', listUnitProperty,...
    'Value', 2);

%% Definition of the grid parameters
handles.title_numXindents_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.02 0.93 0.12 0.02],...
    'String', 'Number of indents along X axis:',...
    'HorizontalAlignment', 'left');

handles.value_numXindents_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'edit',...
    'Position', [0.145 0.93 0.03 0.02],...
    'String', '25');

handles.title_numYindents_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.02 0.91 0.12 0.02],...
    'String', 'Number of indents along Y/Z axis:',...
    'HorizontalAlignment', 'left');

handles.value_numYindents_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'edit',...
    'Position', [0.145 0.91 0.03 0.02],...
    'String', '25');

%% Buttons to browse file
handles.opendata_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [0.02 0.84 0.05 0.06],...
    'String', 'Select file',...
    'FontSize', 10,...
    'FontWeight','bold',...
    'BackgroundColor', [0.745 0.745 0.745],...
    'Callback', 'TriDiMap_loadingMeanData');

handles.opendata_str_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'edit',...
    'Position', [0.075 0.84 0.122 0.06],...
    'String', g.config.data.data_path,...
    'FontSize', 8,...
    'BackgroundColor', [0.9 0.9 0.9],...
    'HorizontalAlignment', 'left');

%% Definition of the distance between indents
handles.title_deltaXindents_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.02 0.81 0.14 0.02],...
    'String', 'Distance between indents along X axis:',...
    'HorizontalAlignment', 'left');

handles.value_deltaXindents_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'edit',...
    'Position', [0.165 0.81 0.03 0.02],...
    'String', num2str(g.config.XStep_default));

handles.unit_deltaXindents_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.195 0.81 0.03 0.02],...
    'String', 'µm',...
    'HorizontalAlignment', 'center');

handles.title_deltaYindents_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.02 0.79 0.14 0.02],...
    'String', 'Distance between indents along Y/Z axis:',...
    'HorizontalAlignment', 'left');

handles.value_deltaYindents_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'edit',...
    'Position', [0.165 0.79 0.03 0.02],...
    'String', num2str(g.config.YStep_default));

handles.unit_deltaYindents_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'text',...
    'Position', [0.195 0.79 0.03 0.02],...
    'String', 'µm',...
    'HorizontalAlignment', 'center');

%% Colorbar options
handles.title_colormap_GUI = uicontrol(...
    'Units', 'normalized',...
    'Style', 'text',...
    'String', 'Colormap:',...
    'HorizontalAlignment', 'left');

handles.colormap_GUI = uicontrol(...
    'Units', 'normalized',...
    'Style', 'popupmenu',...
    'String', listColormap,...
    'Value', 20);

handles.cb_flipColormap_GUI = uicontrol(...
    'Units', 'normalized',...
    'Style', 'checkbox',...
    'String', 'Flip colormap',...
    'Value', 0);

%% Set of the GUI for the mapping step
if module == 1
    %% Definition of the property
    handles.title_property_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.76 0.04 0.02],...
        'String', 'Plot:',...
        'HorizontalAlignment', 'left');
    
    handles.property_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'popupmenu',...
        'Position', [0.06 0.76 0.05 0.02],...
        'String', {'Elastic modulus map';'Hardness map';'E vs H';...
        'E_pdf';'H_pdf';'E_cdf';'H_cdf';'E_pdf+cdf';'H_pdf+cdf'},...
        'Value', g.config.property, ...
        'Callback', 'TriDiMap_runPlot');
    
    coord_bg = [0.015 0.525 0.23 0.22];
    handles.bg_property_GUI_1_2 = uibuttongroup('Visible','on',...
        'Position',coord_bg);
    handles.bg_property_GUI_3 = uibuttongroup('Visible','on',...
        'Position',coord_bg);
    handles.bg_property_GUI_4_5 = uibuttongroup('Visible','on',...
        'Position',coord_bg);
    handles.bg_property_GUI_6_7 = uibuttongroup('Visible','on',...
        'Position',coord_bg);
    
    coord_bg2 = [0.015 0.205 0.23 0.245];
    handles.bg2_property_GUI_1_2 = uibuttongroup('Visible','on',...
        'Position',coord_bg2);
    handles.bg2_property_GUI_3 = uibuttongroup('Visible','on',...
        'Position',coord_bg2);
    handles.bg2_property_GUI_4_5 = uibuttongroup('Visible','on',...
        'Position',coord_bg2);
    handles.bg2_property_GUI_6_7 = uibuttongroup('Visible','on',...
        'Position',coord_bg2);
    
    %% Buttons group for property 1 and 2
    % Crop of the dataset
    handles.title_MinXCrop_GUI = uicontrol('Parent', handles.bg_property_GUI_1_2,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.90 0.38 0.08],...
        'String', 'Minimum indent on X:',...
        'HorizontalAlignment', 'left');
    
    handles.value_MinXCrop_GUI = uicontrol('Parent', handles.bg_property_GUI_1_2,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.40 0.90 0.05 0.08],...
        'String', num2str(1));
    
    handles.title_MaxXCrop_GUI = uicontrol('Parent', handles.bg_property_GUI_1_2,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.80 0.38 0.08],...
        'String', 'Maximum indent on X:',...
        'HorizontalAlignment', 'left');
    
    handles.value_MaxXCrop_GUI = uicontrol('Parent', handles.bg_property_GUI_1_2,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.40 0.80 0.05 0.08],...
        'String', num2str(25));
    
    handles.title_MinYCrop_GUI = uicontrol('Parent', handles.bg_property_GUI_1_2,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.50 0.90 0.38 0.08],...
        'String', 'Minimum indent on Y/Z:',...
        'HorizontalAlignment', 'left');
    
    handles.value_MinYCrop_GUI = uicontrol('Parent', handles.bg_property_GUI_1_2,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.90 0.90 0.05 0.08],...
        'String', num2str(1));
    
    handles.title_MaxYCrop_GUI = uicontrol('Parent', handles.bg_property_GUI_1_2,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.50 0.80 0.38 0.08],...
        'String', 'Maximum indent on Y/Z:',...
        'HorizontalAlignment', 'left');
    
    handles.value_MaxYCrop_GUI = uicontrol('Parent', handles.bg_property_GUI_1_2,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.90 0.80 0.05 0.08],...
        'String', num2str(25));
    
    % 2D / 3D
    handles.pm_pixData_GUI = uicontrol('Parent', handles.bg_property_GUI_1_2,...
        'Units', 'normalized',...
        'Style', 'popupmenu',...
        'Position', [0.02 0.65 0.30 0.12],...
        'String', listPlot,...
        'Value', 1,...
        'Callback', 'TriDiMap_runPlot');
    
    handles.pm_surfShading_GUI = uicontrol('Parent', handles.bg_property_GUI_1_2,...
        'Units', 'normalized',...
        'Style', 'popupmenu',...
        'Position', [0.52 0.65 0.30 0.12],...
        'String', listSurf,...
        'Value', 1,...
        'Callback', 'TriDiMap_runPlot');
    
    handles.cb_meshOption_GUI = uicontrol('Parent', handles.bg_property_GUI_1_2,...
        'Units', 'normalized',...
        'Style', 'checkbox',...
        'Position', [0.52 0.65 0.30 0.12],...
        'String', 'Hidden',...
        'Value', 1,...
        'Callback', 'TriDiMap_runPlot');
    
    handles.title_sliceNum_GUI = uicontrol('Parent', handles.bg_property_GUI_1_2,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.50 0.65 0.38 0.08],...
        'String', 'Number of slices:',...
        'HorizontalAlignment', 'left',...
        'Visible', 'off');
    
    handles.value_sliceNum_GUI = uicontrol('Parent', handles.bg_property_GUI_1_2,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.85 0.65 0.10 0.08],...
        'String', num2str(5),...
        'Visible', 'off');
    
    % Remove NaN pixels (blank pixels)
    handles.cb_pixNaN_GUI = uicontrol('Parent', handles.bg_property_GUI_1_2,...
        'Units', 'normalized',...
        'Style', 'checkbox',...
        'Position', [0.02 0.48 0.48 0.10],...
        'String', 'Remove NaN pixels',...
        'Value', 1,...
        'Callback', 'TriDiMap_runPlot');
    
    handles.title_NaNratio_GUI = uicontrol('Parent', handles.bg_property_GUI_1_2,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.52 0.53 0.15 0.08],...
        'String', 'NaN ratio:',...
        'HorizontalAlignment', 'left');
    
    handles.value_NaNratio_GUI = uicontrol('Parent', handles.bg_property_GUI_1_2,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.69 0.53 0.06 0.08],...
        'String', 2);
    
    handles.unit_NaNratio_GUI = uicontrol('Parent', handles.bg_property_GUI_1_2,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.77 0.53 0.08 0.08],...
        'String', '%',...
        'HorizontalAlignment', 'left');
    
    % Interpolation
    minValI = 1;
    maxValI = 4;
    handles.cb_interpMap_GUI = uicontrol('Parent', handles.bg_property_GUI_1_2,...
        'Units', 'normalized',...
        'Style', 'checkbox',...
        'Position', [0.02 0.38 0.48 0.10],...
        'String', 'Interpolation of the map',...
        'Value', 0,...
        'Callback', 'TriDiMap_runPlot');
    
    handles.pm_interpMap_GUI = uicontrol('Parent', handles.bg_property_GUI_1_2,...
        'Units', 'normalized',...
        'Style', 'popupmenu',...
        'Position', [0.52 0.38 0.30 0.14],...
        'String', listInterp,...
        'Value', 2,...
        'Callback', 'TriDiMap_runPlot');
    
    % Smoothing
    minValS = 1;
    maxValS = 3;
    handles.cb_smoothMap_GUI = uicontrol('Parent', handles.bg_property_GUI_1_2,...
        'Units', 'normalized',...
        'Style', 'checkbox',...
        'Position', [0.02 0.28 0.48 0.10],...
        'String', 'Smoothing of the map',...
        'Value', 0,...
        'Callback', 'TriDiMap_runPlot');
    
    handles.pm_smoothMap_GUI = uicontrol('Parent', handles.bg_property_GUI_1_2,...
        'Units', 'normalized',...
        'Style', 'popupmenu',...
        'Position', [0.52 0.28 0.30 0.12],...
        'String', listSmooth,...
        'Value', 2,...
        'Callback', 'TriDiMap_runPlot');
    
    handles.cb_errorMap_GUI = uicontrol('Parent', handles.bg_property_GUI_1_2,...
        'Units', 'normalized',...
        'Style', 'checkbox',...
        'Position', [0.02 0.18 0.48 0.10],...
        'String', 'Plot of the error map',...
        'Value', 0,...
        'Callback', 'TriDiMap_runPlot');
    
    handles.pm_contourPlotMap_GUI = uicontrol('Parent', handles.bg_property_GUI_1_2, ...
        'Units', 'normalized',...
        'Style', 'popupmenu',...
        'Position', [0.02 0.05 0.45 0.10],...
        'String', listContour,...
        'Value', 1,...
        'Callback', 'TriDiMap_runPlot');
    
    handles.cb_textContourPlotMap_GUI = uicontrol('Parent', handles.bg_property_GUI_1_2, ...
        'Units', 'normalized',...
        'Style', 'checkbox',...
        'Position', [0.52 0.05 0.48 0.10],...
        'String', 'Show text on the map',...
        'Value', 0,...
        'Callback', 'TriDiMap_runPlot');
    
    handles.title_sliceDepthMin_GUI = uicontrol('Parent', handles.bg_property_GUI_1_2,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.09 0.38 0.08],...
        'String', 'Minimum depth (nm):',...
        'HorizontalAlignment', 'left');
    
    handles.value_sliceDepthMin_GUI = uicontrol('Parent', handles.bg_property_GUI_1_2,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.37 0.09 0.10 0.08],...
        'String', num2str(50));
    
    handles.title_sliceDepthMax_GUI = uicontrol('Parent', handles.bg_property_GUI_1_2,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.02 0.38 0.08],...
        'String', 'Maximum depth (nm):',...
        'HorizontalAlignment', 'left');
    
    handles.value_sliceDepthMax_GUI = uicontrol('Parent', handles.bg_property_GUI_1_2,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.37 0.02 0.10 0.08],...
        'String', num2str(100));
    
    handles.pb_gif_GUI = uicontrol('Parent', handles.bg_property_GUI_1_2,...
        'Units', 'normalized',...
        'Style', 'pushbutton',...
        'Position', [0.5 0.02 0.40 0.15],...
        'String', 'Make GIF',...
        'Callback', 'TriDiMap_runPlot(1)',...
        'Visible', 'off');
    
    set([handles.unitLength_GUI, ...
        handles.unitProp_GUI, ...
        handles.value_deltaXindents_GUI, ...
        handles.value_deltaYindents_GUI, ...
        handles.value_MinXCrop_GUI, ...
        handles.value_MinYCrop_GUI, ...
        handles.value_MaxXCrop_GUI, ...
        handles.value_MaxYCrop_GUI, ...
        handles.value_sliceNum_GUI, ...
        handles.value_sliceDepthMin_GUI, ...
        handles.value_sliceDepthMax_GUI],'Callback', 'TriDiMap_runPlot');
    
    %% Buttons group for property 3
    handles.pm_sectPlot_GUI = uicontrol('Parent', handles.bg_property_GUI_3, ...
        'Units', 'normalized',...
        'Style', 'popupmenu',...
        'Position', [0.02 0.80 0.48 0.10],...
        'String', {'No clusters', 'Plot sectors', 'Gaussian Mixture Model'},...
        'Value', 1,...
        'Callback', 'TriDiMap_runPlot');
    
    handles.title_Hth_ValEH_GUI = uicontrol('Parent', handles.bg_property_GUI_3,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.65 0.18 0.10],...
        'String', 'H limit:',...
        'HorizontalAlignment', 'left');
    
    handles.value_Hth_ValEH_GUI = uicontrol('Parent', handles.bg_property_GUI_3,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.22 0.65 0.10 0.10],...
        'String', '10', ...
        'Callback', 'TriDiMap_runPlot');
    
    handles.unit_Hth_ValEH_GUI = uicontrol('Parent', handles.bg_property_GUI_3,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.33 0.65 0.10 0.10],...
        'String', 'GPa',...
        'HorizontalAlignment', 'center');
    
    handles.title_Eth_ValEH_GUI = uicontrol('Parent', handles.bg_property_GUI_3,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.50 0.18 0.10],...
        'String', 'E limit:',...
        'HorizontalAlignment', 'left');
    
    handles.value_Eth_ValEH_GUI = uicontrol('Parent', handles.bg_property_GUI_3,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.22 0.50 0.10 0.10],...
        'String', '200', ...
        'Callback', 'TriDiMap_runPlot');
    
    handles.unit_Eth_ValEH_GUI = uicontrol('Parent', handles.bg_property_GUI_3,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.33 0.50 0.10 0.10],...
        'String', 'GPa',...
        'HorizontalAlignment', 'center');
    
    handles.cb_thresPlot_GUI = uicontrol('Parent', handles.bg_property_GUI_3,...
        'Units', 'normalized',...
        'Style', 'checkbox',...
        'Position', [0.02 0.35 0.48 0.10],...
        'String', 'Plot threshold lines',...
        'Value', 1,...
        'Callback', 'TriDiMap_runPlot');
    
    handles.cb_sectMVPlot_GUI = uicontrol('Parent', handles.bg_property_GUI_3,...
        'Units', 'normalized',...
        'Style', 'checkbox',...
        'Position', [0.02 0.20 0.48 0.10],...
        'String', 'Sectors mean values',...
        'Value', 0,...
        'Callback', 'TriDiMap_runPlot');
    
    handles.cb_plotSectMap_GUI = uicontrol('Parent', handles.bg_property_GUI_3,...
        'Units', 'normalized',...
        'Style', 'checkbox',...
        'Position', [0.02 0.05 0.48 0.10],...
        'String', 'Plot map with sectors',...
        'Value', 0,...
        'Callback', 'TriDiMap_runPlot');
    
    handles.pb_diffEHmapCluster_GUI = uicontrol('Parent', handles.bg_property_GUI_3,...
        'Units', 'normalized',...
        'Style', 'pushbutton',...
        'Position', [0.52 0.05 0.46 0.10],...
        'String', 'Diff Map',...
        'Callback', 'TriDiMap_diffEHmapCluster', ...
        'Visible','off');
    
    handles.title_K_GMM_GUI = uicontrol('Parent', handles.bg_property_GUI_3,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.65 0.18 0.10],...
        'String', 'Phase number:',...
        'HorizontalAlignment', 'left');
    
    handles.value_K_GMM_GUI = uicontrol('Parent', handles.bg_property_GUI_3,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.22 0.65 0.10 0.10],...
        'String', '2', ...
        'Callback', 'TriDiMap_runPlot');
    
    handles.cb_plotEllipse_GUI = uicontrol('Parent', handles.bg_property_GUI_3,...
        'Units', 'normalized',...
        'Style', 'checkbox',...
        'Position', [0.02 0.45 0.80 0.10],...
        'String', 'Plot phase bubbles / Legend',...
        'Value', 0,...
        'Callback', 'TriDiMap_runPlot');
    
    %% Buttons group for property 4 and 5
    handles.title_BinSizeHist_GUI = uicontrol('Parent', handles.bg_property_GUI_4_5,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.85 0.18 0.10],...
        'String', 'Bin size:',...
        'HorizontalAlignment', 'left');
    
    handles.value_BinSizeHist_GUI = uicontrol('Parent', handles.bg_property_GUI_4_5,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.22 0.85 0.10 0.10],...
        'String', '2', ...
        'Callback', 'TriDiMap_runPlot');
    
    handles.unit_BinSizeHist_GUI = uicontrol('Parent', handles.bg_property_GUI_4_5,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.33 0.85 0.10 0.10],...
        'String', 'GPa',...
        'HorizontalAlignment', 'center');
    
    handles.title_MinValHist_GUI = uicontrol('Parent', handles.bg_property_GUI_4_5,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.75 0.18 0.10],...
        'String', 'Min value:',...
        'HorizontalAlignment', 'left');
    
    handles.value_MinValHist_GUI = uicontrol('Parent', handles.bg_property_GUI_4_5,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.22 0.75 0.10 0.10],...
        'String', '0', ...
        'Callback', 'TriDiMap_runPlot');
    
    handles.unit_MinValHist_GUI = uicontrol('Parent', handles.bg_property_GUI_4_5,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.33 0.75 0.10 0.10],...
        'String', 'GPa',...
        'HorizontalAlignment', 'center');
    
    handles.title_MaxValHist_GUI = uicontrol('Parent', handles.bg_property_GUI_4_5,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.65 0.18 0.10],...
        'String', 'Max value:',...
        'HorizontalAlignment', 'left');
    
    handles.value_MaxValHist_GUI = uicontrol('Parent', handles.bg_property_GUI_4_5,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.22 0.65 0.10 0.10],...
        'String', '400', ...
        'Callback', 'TriDiMap_runPlot');
    
    handles.unit_MaxValHist_GUI = uicontrol('Parent', handles.bg_property_GUI_4_5,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.33 0.65 0.10 0.10],...
        'String', 'GPa',...
        'HorizontalAlignment', 'center');
    
    handles.cb_autoBinSizeHist_GUI = uicontrol('Parent', handles.bg_property_GUI_4_5,...
        'Units', 'normalized',...
        'Style', 'checkbox',...
        'Position', [0.50 0.85 0.50 0.10],...
        'String', 'Auto Bin Size',...
        'Value', 0, ...
        'Callback', 'TriDiMap_runPlot');
    
    handles.cb_deconvolutionHist_GUI = uicontrol('Parent', handles.bg_property_GUI_4_5,...
        'Units', 'normalized',...
        'Style', 'checkbox',...
        'Position', [0.02 0.45 0.50 0.10],...
        'String', 'Deconvolution',...
        'Value', 0,...
        'Callback', 'TriDiMap_runPlot');
    
    handles.cb_colorHist_GUI = uicontrol('Parent', handles.bg_property_GUI_4_5,...
        'Units', 'normalized',...
        'Style', 'checkbox',...
        'Position', [0.28 0.45 0.50 0.10],...
        'String', 'Multicolor Plot',...
        'Value', 0,...
        'Callback', 'TriDiMap_runPlot');
    
    handles.title_PhNumHist_GUI = uicontrol('Parent', handles.bg_property_GUI_4_5,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.32 0.26 0.10],...
        'String', 'Phase number:',...
        'HorizontalAlignment', 'left');
    
    handles.value_PhNumHist_GUI = uicontrol('Parent', handles.bg_property_GUI_4_5,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.28 0.32 0.10 0.10],...
        'String', '2', ...
        'Callback', 'TriDiMap_runPlot');
    
    handles.title_PhNumHist_GUI = uicontrol('Parent', handles.bg_property_GUI_4_5,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.40 0.32 0.26 0.10],...
        'String', '(6 max)',...
        'HorizontalAlignment', 'left');
    
    handles.title_IterMaxHist_GUI = uicontrol('Parent', handles.bg_property_GUI_4_5,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.22 0.26 0.10],...
        'String', 'Iteration max:',...
        'HorizontalAlignment', 'left');
    
    handles.value_IterMaxHist_GUI = uicontrol('Parent', handles.bg_property_GUI_4_5,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.28 0.22 0.10 0.10],...
        'String', '50', ...
        'Callback', 'TriDiMap_runPlot');
    
    handles.title_PrecHist_GUI = uicontrol('Parent', handles.bg_property_GUI_4_5,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.12 0.26 0.10],...
        'String', 'Precision:',...
        'HorizontalAlignment', 'left');
    
    handles.value_PrecHist_GUI = uicontrol('Parent', handles.bg_property_GUI_4_5,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.28 0.12 0.10 0.10],...
        'String', '1e-6', ...
        'Callback', 'TriDiMap_runPlot');
    
    handles.title_IterResHist_GUI = uicontrol('Parent', handles.bg_property_GUI_4_5,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.55 0.22 0.26 0.10],...
        'String', 'Iteration n°:',...
        'HorizontalAlignment', 'left');
    
    handles.value_IterResHist_GUI = uicontrol('Parent', handles.bg_property_GUI_4_5,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.81 0.22 0.10 0.10],...
        'String', '50', ...
        'Callback', 'TriDiMap_runPlot');
    
    handles.title_PrecHistRes_GUI = uicontrol('Parent', handles.bg_property_GUI_4_5,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.55 0.12 0.26 0.10],...
        'String', 'Prec. obtained:',...
        'HorizontalAlignment', 'left');
    
    handles.value_PrecHistRes_GUI = uicontrol('Parent', handles.bg_property_GUI_4_5,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.81 0.12 0.10 0.10],...
        'String', '1e-6', ...
        'Callback', 'TriDiMap_runPlot');
    
    handles.cb_plotErrorPDF_GUI = uicontrol('Parent', handles.bg_property_GUI_4_5,...
        'Units', 'normalized',...
        'Style', 'checkbox',...
        'Position', [0.02 0.02 0.50 0.10],...
        'String', 'Plot error',...
        'Tag', 'PlotErrorPDF',...
        'Value', 0,...
        'Callback', 'TriDiMap_runPlot');
    
    %% Buttons group for property 6 and 7
    handles.title_MinValCDF_GUI = uicontrol('Parent', handles.bg_property_GUI_6_7,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.85 0.18 0.10],...
        'String', 'Min value:',...
        'HorizontalAlignment', 'left');
    
    handles.value_MinValCDF_GUI = uicontrol('Parent', handles.bg_property_GUI_6_7,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.22 0.85 0.10 0.10],...
        'String', '0', ...
        'Callback', 'TriDiMap_runPlot');
    
    handles.unit_MinValCDF_GUI = uicontrol('Parent', handles.bg_property_GUI_6_7,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.33 0.85 0.10 0.10],...
        'String', 'GPa',...
        'HorizontalAlignment', 'center');
    
    handles.title_MaxValCDF_GUI = uicontrol('Parent', handles.bg_property_GUI_6_7,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.75 0.18 0.10],...
        'String', 'Max value:',...
        'HorizontalAlignment', 'left');
    
    handles.value_MaxValCDF_GUI = uicontrol('Parent', handles.bg_property_GUI_6_7,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.22 0.75 0.10 0.10],...
        'String', '400', ...
        'Callback', 'TriDiMap_runPlot');
    
    handles.unit_MaxValCDF_GUI = uicontrol('Parent', handles.bg_property_GUI_6_7,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.33 0.75 0.10 0.10],...
        'String', 'GPa',...
        'HorizontalAlignment', 'center');
    
    handles.cb_WeibullFit_GUI = uicontrol('Parent', handles.bg_property_GUI_6_7,...
        'Units', 'normalized',...
        'Style', 'checkbox',...
        'Position', [0.02 0.50 0.50 0.10],...
        'String', 'Weibull fit',...
        'Value', 0,...
        'Callback', 'TriDiMap_runPlot');
    
    %% Min, Mean and Max values of the property
    handles.title_MinVal_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.50 0.09 0.02],...
        'String', 'Minimum property value:',...
        'HorizontalAlignment', 'left');
    
    handles.value_MinVal_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.115 0.50 0.03 0.02],...
        'String', num2str(g.config.cminOld),...
        'Callback', 'TriDiMap_runPlot');
    
    handles.unit_MinVal_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.145 0.50 0.03 0.02],...
        'String', 'GPa',...
        'HorizontalAlignment', 'center');
    
    handles.title_MeanVal_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.48 0.09 0.02],...
        'String', 'Mean property value:',...
        'HorizontalAlignment', 'left');
    
    handles.value_MeanVal_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.115 0.48 0.03 0.02],...
        'String', num2str(g.config.cmaxOld),...
        'Callback', 'TriDiMap_runPlot');
    
    handles.unit_MeanVal_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.145 0.48 0.03 0.02],...
        'String', 'GPa',...
        'HorizontalAlignment', 'center');
    
    handles.title_StdVal_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.177 0.48 0.012 0.02],...
        'String', '+/-',...
        'HorizontalAlignment', 'left');
    
    handles.value_StdVal_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.19 0.48 0.03 0.02],...
        'String', num2str(g.config.cmaxOld),...
        'Callback', 'TriDiMap_runPlot');
    
    handles.unit_StdVal_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.22 0.48 0.03 0.02],...
        'String', 'GPa',...
        'HorizontalAlignment', 'center');
    
    
    handles.title_MaxVal_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.46 0.09 0.02],...
        'String', 'Maximum property value:',...
        'HorizontalAlignment', 'left');
    
    handles.value_MaxVal_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.115 0.46 0.03 0.02],...
        'String', num2str(g.config.cmaxOld),...
        'Callback', 'TriDiMap_runPlot');
    
    handles.unit_MaxVal_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.145 0.46 0.03 0.02],...
        'String', 'GPa',...
        'HorizontalAlignment', 'center');
    
    %% Colorbar options
    set(handles.title_colormap_GUI, ...
        'Parent', handles.bg2_property_GUI_1_2, ...
        'Position', [0.02 0.91 0.15 0.08]);
    set(handles.colormap_GUI, ...
        'Position', [0.20 0.91 0.30 0.08],...
        'Parent', handles.bg2_property_GUI_1_2, ...
        'Callback', 'TriDiMap_runPlot');
    set(handles.cb_flipColormap_GUI, ...
        'Parent', handles.bg2_property_GUI_1_2, ...
        'Position', [0.55 0.91 0.30 0.08],...
        'Callback', 'TriDiMap_runPlot');
    
    handles.cb_markers_GUI = uicontrol('Parent', handles.bg2_property_GUI_1_2, ...
        'Units', 'normalized',...
        'Style', 'checkbox',...
        'String', 'Markers',...
        'Position', [0.55 0.78 0.30 0.08],...
        'Value', 0,...
        'Callback', 'TriDiMap_runPlot');
    
    handles.cb_autoColorbar_GUI = uicontrol('Parent', handles.bg2_property_GUI_1_2, ...
        'Units', 'normalized',...
        'Style', 'checkbox',...
        'Position', [0.02 0.78 0.40 0.08],...
        'String', 'Auto colorbar',...
        'Value', 0,...
        'Callback', 'TriDiMap_runPlot');
    
    handles.title_colorMin_GUI = uicontrol('Parent', handles.bg2_property_GUI_1_2, ...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.67 0.15 0.08],...
        'String', 'Minimum colorbar value:',...
        'HorizontalAlignment', 'left');
    
    handles.value_colorMin_GUI = uicontrol('Parent', handles.bg2_property_GUI_1_2, ...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.20 0.67 0.08 0.08],...
        'String', num2str(g.config.cminOld),...
        'Callback', 'TriDiMap_runPlot');
    
    handles.unit_colorMin_GUI = uicontrol('Parent', handles.bg2_property_GUI_1_2, ...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.30 0.67 0.08 0.08],...
        'String', 'GPa',...
        'HorizontalAlignment', 'center');
    
    handles.title_colorMax_GUI = uicontrol('Parent', handles.bg2_property_GUI_1_2, ...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.56 0.15 0.08],...
        'String', 'Maximum colorbar value:',...
        'HorizontalAlignment', 'left');
    
    handles.value_colorMax_GUI = uicontrol('Parent', handles.bg2_property_GUI_1_2, ...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.20 0.56 0.08 0.08],...
        'String', num2str(g.config.cmaxOld),...
        'Callback', 'TriDiMap_runPlot');
    
    handles.unit_colorMax_GUI = uicontrol('Parent', handles.bg2_property_GUI_1_2, ...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.30 0.56 0.08 0.08],...
        'String', 'GPa',...
        'HorizontalAlignment', 'center');
    
    handles.title_colorNum_GUI = uicontrol('Parent', handles.bg2_property_GUI_1_2, ...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.45 0.30 0.08],...
        'String', 'Number of intervals:',...
        'HorizontalAlignment', 'left');
    
    handles.value_colorNum_GUI = uicontrol('Parent', handles.bg2_property_GUI_1_2, ...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.35 0.45 0.08 0.08],...
        'String', '10',...
        'Callback', 'TriDiMap_runPlot');
    
    %% Normalization of the colorbar
    handles.cb_normMap_GUI = uicontrol('Parent', handles.bg2_property_GUI_1_2, ...
        'Units', 'normalized',...
        'Style', 'checkbox',...
        'Position', [0.02 0.34 0.50 0.08],...
        'String', 'Normalization of the colorbar',...
        'Value', 0,...
        'Callback', 'TriDiMap_runPlot');
    
    handles.pm_normMap_GUI = uicontrol('Parent', handles.bg2_property_GUI_1_2, ...
        'Units', 'normalized',...
        'Style', 'popupmenu',...
        'Position', [0.55 0.34 0.20 0.08],...
        'String', listVal,...
        'Value', 2,...
        'Callback', 'TriDiMap_runPlot');
    
    %% Translation of the colorbar
    handles.cb_transMap_GUI = uicontrol('Parent', handles.bg2_property_GUI_1_2, ...
        'Units', 'normalized',...
        'Style', 'checkbox',...
        'Position', [0.02 0.21 0.50 0.08],...
        'String', 'Translation of the colorbar',...
        'Value', 0,...
        'Callback', 'TriDiMap_runPlot');
    
    handles.value_transMap_GUI = uicontrol('Parent', handles.bg2_property_GUI_1_2, ...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.55 0.21 0.08 0.08],...
        'String', '10',...
        'Callback', 'TriDiMap_runPlot');
    
    handles.unit_transMap_GUI = uicontrol('Parent', handles.bg2_property_GUI_1_2, ...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.65 0.21 0.08 0.08],...
        'String', 'GPa',...
        'HorizontalAlignment', 'center');
    
    %% Options of the plot
    handles.title_zAxisRatio_GUI = uicontrol('Parent', handles.bg2_property_GUI_1_2, ...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.10 0.25 0.08],...
        'String', 'Z axis ratio:',...
        'HorizontalAlignment', 'left');
    
    handles.value_zAxisRatio_GUI = uicontrol('Parent', handles.bg2_property_GUI_1_2, ...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.25 0.10 0.08 0.08],...
        'String', 2,...
        'Callback', 'TriDiMap_runPlot');
    
    handles.title_alphaMap_GUI = uicontrol('Parent', handles.bg2_property_GUI_1_2, ...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.02 0.25 0.08],...
        'String', 'Transparency (alpha):',...
        'HorizontalAlignment', 'left');
    
    handles.value_alphaMap_GUI = uicontrol('Parent', handles.bg2_property_GUI_1_2, ...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.25 0.02 0.08 0.08],...
        'String', 0.1,...
        'Callback', 'TriDiMap_runPlot');
    
    %% Options of the plot
    handles.cb_log_plot_GUI = uicontrol('Parent', gcf, ...
        'Units', 'normalized',...
        'Style', 'checkbox',...
        'Position', [0.02 0.17 0.05 0.03],...
        'String', 'Log',...
        'Value', 0,...
        'Callback', 'TriDiMap_runPlot');
    
    handles.cb_grid_plot_GUI = uicontrol('Parent', gcf, ...
        'Units', 'normalized',...
        'Style', 'checkbox',...
        'Position', [0.07 0.17 0.05 0.03],...
        'String', 'Grid',...
        'Value', 0,...
        'Callback', 'TriDiMap_runPlot');
    
    if ~strcmp(g.config.MatlabRelease, '(R2014b)')
        handles.cb_tickColorBar_GUI = uicontrol('Parent', gcf, ...
            'Units', 'normalized',...
            'Style', 'checkbox',...
            'Position', [0.12 0.17 0.05 0.03],...
            'String', 'Ticks',...
            'Value', 0,...
            'Callback', 'TriDiMap_runPlot');
    end
    
    handles.cb_MinMax_plot_GUI = uicontrol('Parent', gcf, ...
        'Units', 'normalized',...
        'Style', 'checkbox',...
        'Position', [0.17 0.17 0.05 0.03],...
        'String', 'Min/Max',...
        'Value', 0,...
        'Callback', 'TriDiMap_runPlot');
    
    %% Location of the legend
    % handles.title_legend_location = uicontrol('Parent', gcf,...
    %     'Units', 'normalized',...
    %     'Style', 'text',...
    %     'Position', [0.02 0.22 0.04 0.02],...
    %     'String', 'Legend location:',...
    %     'HorizontalAlignment', 'left');
    %
    % handles.legend_GUI = uicontrol('Parent', gcf,...
    %     'Units', 'normalized',...
    %     'Style', 'popupmenu',...
    %     'Position', [0.06 0.22 0.05 0.02],...
    %     'String', listLocationLegend,...
    %     'Value', 2,...
    %     'Callback', 'TriDiMap_runPlot');
    
    %% Get values from plot
    handles.pb_get_values_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'pushbutton',...
        'Position', [0.02 0.14 0.1 0.03],...
        'String', 'Get property value',...
        'Callback', 'plot_get_values');
    
    handles.title_x_values_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.12 0.03 0.02],...
        'String', 'X value:',...
        'HorizontalAlignment', 'left');
    
    handles.value_x_values_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.05 0.12 0.03 0.02],...
        'String', '');
    
    handles.unit_x_values_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.08 0.12 0.03 0.02],...
        'String', '',...
        'HorizontalAlignment', 'left');
    
    handles.title_y_values_prop_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.10 0.03 0.02],...
        'String', 'Y value:',...
        'HorizontalAlignment', 'left');
    
    handles.value_y_values_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.05 0.10 0.03 0.02],...
        'String', '');
    
    handles.unit_y_values_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.08 0.10 0.03 0.02],...
        'String', '',...
        'HorizontalAlignment', 'left');
    
    handles.title_z_values_prop_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.12 0.11 0.03 0.02],...
        'String', 'Property:',...
        'HorizontalAlignment', 'left');
    
    handles.value_z_values_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.15 0.11 0.03 0.02],...
        'String', '');
    
    handles.unit_z_values_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.18 0.11 0.03 0.02],...
        'String', '',...
        'HorizontalAlignment', 'left');
    
    %% Plot configuration
    handles.AxisPlot_GUI = axes('Parent', gcf,...
        'Position', [0.33 0.10 0.60 0.75]);
    
    set(gcf,'CurrentAxes', handles.AxisPlot_GUI);
end

%% Others buttons
% Save
handles.save_GUI = uicontrol('Parent', gcf,...
    'Units', 'normalized',...
    'Style', 'pushbutton',...
    'Position', [0.02 0.03 0.05 0.06],...
    'String', 'SAVE',...
    'Callback', 'save_figure', ...
    'FontSize', 12,...
    'BackgroundColor', [0.745 0.745 0.745]);

PosButt = [0.08 0.03 0.09 0.06];
if module == 1
    % Binarization
    handles.binarization_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'pushbutton',...
        'Position', PosButt,...
        'String', 'BINARIZATION',...
        'Callback', 'TriDiMap_switchFunc', ...
        'FontSize', 12,...
        'BackgroundColor', [0.745 0.745 0.745]);
    
    handles.saveXLS_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'pushbutton',...
        'Position', [0.18 0.03 0.05 0.06],...
        'String', 'XLS',...
        'Callback', 'TriDiMap_saveExcel', ...
        'FontSize', 12,...
        'BackgroundColor', [0.745 0.745 0.745]);
    
    handles.ThreeDplot_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'pushbutton',...
        'Position', [0.24 0.03 0.05 0.06],...
        'String', 'Z plot',...
        'Callback', 'TriDiMap_runZplot', ...
        'FontSize', 12,...
        'BackgroundColor', [0.745 0.745 0.745]);
    
elseif module == 2
    handles.binarization_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'pushbutton',...
        'Position', PosButt,...
        'String', 'MAPPING',...
        'Callback', 'TriDiMap_switchFunc', ...
        'FontSize', 12,...
        'BackgroundColor', [0.745 0.745 0.745]);
    
    handles.plotEH_cleaned = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'pushbutton',...
        'Position', [0.18 0.03 0.05 0.06],...
        'String', 'E vs H',...
        'Callback', 'TriDiMap_plotEH_cleaned', ...
        'FontSize', 12,...
        'BackgroundColor', [0.745 0.745 0.745]);
    
    handles.EH_corrPlot_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'pushbutton',...
        'Position', [0.24 0.03 0.05 0.06],...
        'String', 'Corr. map',...
        'Callback', 'TriDiMap_EH_corrPlot', ...
        'FontSize', 12,...
        'BackgroundColor', [0.745 0.745 0.745]);
end

%% Set of the GUI for the binarization step
if module == 2
    handles.title_MinXCrop_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.77 0.08 0.02],...
        'String', 'Minimum indent on X',...
        'HorizontalAlignment', 'left');
    
    handles.value_MinXCrop_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.10 0.77 0.02 0.02],...
        'String', num2str(1),...
        'Callback', 'TriDiMap_runBin');
    
    handles.title_MaxXCrop_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.75 0.08 0.02],...
        'String', 'Maximum indent on X',...
        'HorizontalAlignment', 'left');
    
    handles.value_MaxXCrop_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.10 0.75 0.02 0.02],...
        'String', num2str(25),...
        'Callback', 'TriDiMap_runBin');
    
    handles.title_MinYCrop_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.125 0.77 0.08 0.02],...
        'String', 'Minimum indent on Y/Z',...
        'HorizontalAlignment', 'left');
    
    handles.value_MinYCrop_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.21 0.77 0.02 0.02],...
        'String', num2str(1),...
        'Callback', 'TriDiMap_runBin');
    
    handles.title_MaxYCrop_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.125 0.75 0.08 0.02],...
        'String', 'Maximum indent on Y/Z',...
        'HorizontalAlignment', 'left');
    
    handles.value_MaxYCrop_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.21 0.75 0.02 0.02],...
        'String', num2str(25),...
        'Callback', 'TriDiMap_runBin');
    
    set(handles.unitLength_GUI ,'Callback', 'TriDiMap_runBin');
    set(handles.unitProp_GUI ,'Callback', 'TriDiMap_runBin');
    set(handles.value_deltaXindents_GUI ,'Callback', 'TriDiMap_runBin');
    set(handles.value_deltaYindents_GUI ,'Callback', 'TriDiMap_runBin');
    
    %% Definition of the criterion
    handles.title_criterionE_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.72 0.14 0.02],...
        'String', 'Threshold for the elastic modulus:',...
        'HorizontalAlignment', 'left');
    
    handles.value_criterionE_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.165 0.72 0.03 0.02],...
        'String', 250,...
        'Callback', 'TriDiMap_runBin');
    
    handles.unit_criterionE_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.195 0.72 0.03 0.02],...
        'String', 'GPa',...
        'HorizontalAlignment', 'center');
    
    handles.title_criterionH_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.70 0.14 0.02],...
        'String', 'Threshold for the hardness:',...
        'HorizontalAlignment', 'left');
    
    handles.value_criterionH_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.165 0.70 0.03 0.02],...
        'String', 10,...
        'Callback', 'TriDiMap_runBin');
    
    handles.unit_criterionH_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.195 0.70 0.03 0.02],...
        'String', 'GPa',...
        'HorizontalAlignment', 'center');
    
    handles.optCritVal_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'pushbutton',...
        'Position', [0.02 0.66 0.20 0.04],...
        'String', 'Optimization of threshold',...
        'FontSize', 10,...
        'FontWeight','bold',...
        'BackgroundColor', [0.745 0.745 0.745],...
        'Visible', 'off', ...
        'Callback', 'TriDiMap_optThreshold');
    
    handles.title_numThres_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.63 0.11 0.02],...
        'String', 'Number of threshold:',...
        'HorizontalAlignment', 'left', ...
        'Visible', 'off');
    
    handles.value_numThres_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.165 0.63 0.03 0.02],...
        'String', '20', ...
        'Visible', 'off');
    
    handles.plotAllCritVal_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'pushbutton',...
        'Position', [0.02 0.58 0.20 0.04],...
        'String', 'Plot of match = f(all threshold)',...
        'FontSize', 10,...
        'FontWeight','bold',...
        'BackgroundColor', [0.745 0.745 0.745],...
        'Visible', 'off', ...
        'Callback', 'TriDiMap_plotMatchThreshold');
    
    %% Buttons to browse image
    handles.openimage_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'pushbutton',...
        'Position', [0.02 0.50 0.05 0.06],...
        'String', 'Get Image',...
        'FontSize', 10,...
        'FontWeight','bold',...
        'BackgroundColor', [0.745 0.745 0.745],...
        'Callback', 'TriDiMap_loadingImage');
    
    handles.openimage_str_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.075 0.50 0.122 0.06],...
        'String', g.config.image.image_path,...
        'FontSize', 8,...
        'BackgroundColor', [0.9 0.9 0.9],...
        'HorizontalAlignment', 'left');
    
    %% Colorbar options
    set(handles.title_colormap_GUI, ...
        'Parent', gcf,...
        'Position', [0.02 0.46 0.04 0.02]);
    set(handles.colormap_GUI, ...
        'Parent', gcf,...
        'Position', [0.06 0.46 0.05 0.02],...
        'Callback', 'TriDiMap_runBin', ...
        'Value', 8);
    set(handles.cb_flipColormap_GUI, ...
        'Parent', gcf,...
        'Position', [0.115 0.46 0.085 0.02],...
        'Callback', 'TriDiMap_runBin');
    
    %% Match settings
    handles.title_pixelList_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'String', 'Pixels:',...
        'HorizontalAlignment', 'left', ...
        'Position', [0.02 0.42 0.04 0.02]);
    
    handles.pixelList_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'popupmenu',...
        'String', listPixel,...
        'Value', 1, ...
        'Position', [0.06 0.42 0.05 0.02],...
        'Callback', 'TriDiMap_runBin');
    
    %% Difference calculations
    handles.title_diffValE_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.36 0.13 0.02],...
        'String', 'Match between E map and image',...
        'HorizontalAlignment', 'left');
    
    handles.value_diffValE_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.155 0.36 0.03 0.02]);
    
    handles.unit_diffValE_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.190 0.36 0.03 0.02],...
        'String', '%',...
        'HorizontalAlignment', 'left');
    
    handles.title_diffValH_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.33 0.13 0.02],...
        'String', 'Match between H map and image',...
        'HorizontalAlignment', 'left');
    
    handles.value_diffValH_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.155 0.33 0.03 0.02]);
    
    handles.unit_diffValH_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.190 0.33 0.03 0.02],...
        'String', '%',...
        'HorizontalAlignment', 'left');
    
    handles.title_diffValEH_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.02 0.30 0.13 0.02],...
        'String', 'Match between E and H maps',...
        'HorizontalAlignment', 'left');
    
    handles.value_diffValEH_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [0.155 0.30 0.03 0.02]);
    
    handles.unit_diffValEH_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [0.190 0.30 0.03 0.02],...
        'String', '%',...
        'HorizontalAlignment', 'left');
    
    %% Phases ratios calculations
    x1 = 0.02; x2 = 0.08; x3 = 0.11; x4 = 0.13; x5 = 0.21; x6 = 0.24;
    y = 0.26;
    w1 = 0.06; w2 = 0.03; w3 = 0.01; w4 = 0.08;
    h = 0.02;
    
    handles.title_ratioLow_E_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [x1 y w1 h],...
        'String', 'E - Soft phase',...
        'HorizontalAlignment', 'left');
    
    handles.value_ratioLow_E_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [x2 y w2 h]);
    
    handles.unit_ratioLow_E_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [x3 y w3 h],...
        'String', '%',...
        'HorizontalAlignment', 'left');
    
    handles.title_ratioHigh_E_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [x4 y w4 h],...
        'String', 'E - Hard/stiff phase',...
        'HorizontalAlignment', 'left');
    
    handles.value_ratioHigh_E_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [x5 y w2 h]);
    
    handles.unit_ratioHigh_E_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [x6 y w3 h],...
        'String', '%',...
        'HorizontalAlignment', 'left');
    
    handles.title_ratioLow_H_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [x1 y-0.03 w1 h],...
        'String', 'H - Soft phase',...
        'HorizontalAlignment', 'left');
    
    handles.value_ratioLow_H_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [x2 y-0.03 w2 h]);
    
    handles.unit_ratioLow_H_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [x3 y-0.03 w3 h],...
        'String', '%',...
        'HorizontalAlignment', 'left');
    
    handles.title_ratioHigh_H_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [x4 y-0.03 w4 h],...
        'String', 'H - Hard/stiff phase',...
        'HorizontalAlignment', 'left');
    
    handles.value_ratioHigh_H_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [x5 y-0.03 w2 h]);
    
    handles.unit_ratioHigh_H_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [x6 y-0.03 w3 h],...
        'String', '%',...
        'HorizontalAlignment', 'left');
    
    handles.title_ratioLow_I_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [x1 y-0.06 w1 h],...
        'String', 'I - Soft phase',...
        'HorizontalAlignment', 'left');
    
    handles.value_ratioLow_I_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [x2 y-0.06 w2 h]);
    
    handles.unit_ratioLow_I_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [x3 y-0.06 w3 h],...
        'String', '%',...
        'HorizontalAlignment', 'left');
    
    handles.title_ratioHigh_I_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [x4 y-0.06 w4 h],...
        'String', 'I - Fraction of hard/stiff phase',...
        'HorizontalAlignment', 'left');
    
    handles.value_ratioHigh_I_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [x5 y-0.06 w2 h]);
    
    handles.unit_ratioHigh_I_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [x6 y-0.06 w3 h],...
        'String', '%',...
        'HorizontalAlignment', 'left');
    
    %% Mean values
    x1 = 0.02; x2 = 0.07; x3 = 0.11; x4 = 0.135; x5 = 0.2; x6 = 0.24;
    y = 0.17;
    w1 = 0.06; w2 = 0.04; w3 = 0.02;
    h = 0.02;
    
    handles.title_valMeanLow_E_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [x1 y w1 h],...
        'String', 'Mean E - Soft',...
        'HorizontalAlignment', 'left');
    
    handles.value_valMeanLow_E_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [x2 y w2 h]);
    
    handles.unit_valMeanLow_E_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [x3 y w3 h],...
        'String', 'GPa',...
        'HorizontalAlignment', 'left');
    
    handles.title_valMeanHigh_E_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [x4 y w4 h],...
        'String', 'Mean E - Hard',...
        'HorizontalAlignment', 'left');
    
    handles.value_valMeanHigh_E_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [x5 y w2 h]);
    
    handles.unit_valMeanHigh_E_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [x6 y w3 h],...
        'String', 'GPa',...
        'HorizontalAlignment', 'left');
    
    handles.title_valMeanLow_H_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [x1 y-0.03 w1 h],...
        'String', 'Mean H - Soft',...
        'HorizontalAlignment', 'left');
    
    handles.value_valMeanLow_H_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [x2 y-0.03 w2 h]);
    
    handles.unit_valMeanLow_H_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [x3 y-0.03 w3 h],...
        'String', 'GPa',...
        'HorizontalAlignment', 'left');
    
    handles.title_valMeanHigh_H_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [x4 y-0.03 w4 h],...
        'String', 'Mean H - Hard',...
        'HorizontalAlignment', 'left');
    
    handles.value_valMeanHigh_H_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'edit',...
        'Position', [x5 y-0.03 w2 h]);
    
    handles.unit_valMeanHigh_H_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [x6 y-0.03 w3 h],...
        'String', 'GPa',...
        'HorizontalAlignment', 'left');
    
    %% Legend
    % handles.title_legend_location = uicontrol('Parent', gcf,...
    %     'Units', 'normalized',...
    %     'Style', 'text',...
    %     'Position', [0.02 0.13 0.04 0.02],...
    %     'String', 'Legend location:',...
    %     'HorizontalAlignment', 'left');
    %
    % handles.legend_GUI = uicontrol('Parent', gcf,...
    %     'Units', 'normalized',...
    %     'Style', 'popupmenu',...
    %     'Position', [0.06 0.13 0.05 0.02],...
    %     'String', listLocationLegend,...
    %     'Value', 2,...
    %     'Callback', 'TriDiMap_runPlot');
    handles.cb_legend_GUI = uicontrol('Parent', gcf,...
        'Units', 'normalized',...
        'Style', 'checkbox',...
        'Position', [0.115 0.42 0.04 0.02],...
        'String', 'Legend',...
        'Value', 1,...
        'Callback', 'TriDiMap_runBin');
    
    %% Plot configuration
    handles.AxisPlot_GUI_1 = axes('Parent', gcf,...
        'Position', [0.3 0.55 0.15 0.30]);
    
    handles.AxisPlot_GUI_2 = axes('Parent', gcf,...
        'Position', [0.5 0.55 0.15 0.30]);
    
    handles.AxisPlot_GUI_3 = axes('Parent', gcf,...
        'Position', [0.7 0.55 0.15 0.30]);
    
    handles.AxisPlot_GUI_4 = axes('Parent', gcf,...
        'Position', [0.3 0.10 0.15 0.30]);
    
    handles.AxisPlot_GUI_5 = axes('Parent', gcf,...
        'Position', [0.5 0.10 0.15 0.30]);
    
    handles.AxisPlot_GUI_6 = axes('Parent', gcf,...
        'Position', [0.7 0.10 0.15 0.30]);
    
end

%% Coordinates system
coordSyst(handles.MainWindow);
g = guidata(gcf);

%% Guidata
g.handles = handles;
guidata(gcf, g);

%% Update units
TriDiMap_updateUnit_and_GUI;

end