%% Copyright 2014 MERCIER David
function coordSyst(handle)
%% Function to plot coordinate systems
gui = guidata(gcf);

set(0, 'currentfigure', handle);

xVal = 0.93;
yVal = 0.89;
arrowLength = 0.03;

if ~gui.config.flagZplot
    try
        delete(findall(gcf,'Tag','annotation'));
    catch
    end
    xX = [xVal, xVal + arrowLength];
    yX = [yVal, yVal];
    gui.handlesCS.arrowX = annotation('arrow',xX,yX,'Tag','annotation');
    gui.handlesCS.textX = uicontrol('Parent', handle,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [xVal+arrowLength yVal-0.01 0.02 0.02],...
        'String', 'X',...
        'Tag','annotation');
    xY = [xVal, xVal];
    yY = [yVal, yVal + 2*arrowLength];
    gui.handlesCS.arrowY = annotation('arrow',xY,yY,'Tag','annotation');
    gui.handlesCS.textY = uicontrol('Parent', handle,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [xVal-0.01 yVal+2*arrowLength 0.02 0.02],...
        'String', 'Y',...
        'Tag','annotation');
else
    try
        delete(findall(gcf,'Tag','annotation'));
    catch
    end
    xX = [xVal, xVal + arrowLength];
    yX = [yVal + 2*arrowLength, yVal + 2*arrowLength];
    gui.handlesCS.arrowX = annotation('arrow',xX,yX,'Tag','annotation');
    gui.handlesCS.textX = uicontrol('Parent', handle,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [xVal+arrowLength yVal-0.01+ 2*arrowLength 0.02 0.02],...
        'String', 'X',...
        'Tag','annotation');
    xY = [xVal, xVal];
    yY = [yVal + 2*arrowLength, yVal];
    gui.handlesCS.arrowY = annotation('arrow',xY,yY,'Tag','annotation');
    gui.handlesCS.textY = uicontrol('Parent', handle,...
        'Units', 'normalized',...
        'Style', 'text',...
        'Position', [xVal-0.01 yVal-arrowLength-0.01 0.02 0.02],...
        'String', 'Z',...
        'Tag','annotation');
end

guidata(gcf, gui);
end